"""workflow dates and status history

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 05:01:30.687883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_status_history',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_status_history_content_item_id'), 'content_status_history', ['content_item_id'], unique=False)
    op.add_column('campaigns', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('content_items', sa.Column('planned_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_content_items_planned_date'), 'content_items', ['planned_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_items_planned_date'), table_name='content_items')
    op.drop_column('content_items', 'planned_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_index(op.f('ix_content_status_history_content_item_id'), table_name='content_status_history')
    op.drop_table('content_status_history')
    # ### end Alembic commands ###
