"""publications

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 05:53:21.728565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('content_item_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=1000), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_content_item_id'), 'publications', ['content_item_id'], unique=False)
    op.create_index(op.f('ix_publications_project_id'), 'publications', ['project_id'], unique=False)
    op.create_index(op.f('ix_publications_scheduled_at'), 'publications', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_publications_status'), 'publications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_status'), table_name='publications')
    op.drop_index(op.f('ix_publications_scheduled_at'), table_name='publications')
    op.drop_index(op.f('ix_publications_project_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_content_item_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
