"""social connections

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 06:30:08.594555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_pending',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('payload_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_pending_project_id'), 'meta_pending', ['project_id'], unique=False)
    op.create_table('social_connections',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'platform', name='uq_social_project_platform')
    )
    op.create_index(op.f('ix_social_connections_project_id'), 'social_connections', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_connections_project_id'), table_name='social_connections')
    op.drop_table('social_connections')
    op.drop_index(op.f('ix_meta_pending_project_id'), table_name='meta_pending')
    op.drop_table('meta_pending')
    # ### end Alembic commands ###
